#!/usr/bin/env python3
# vim:ts=4:sw=4:ft=python:fileencoding=utf-8

# Feed2toot startup
'''Feed2toot startup'''

import sys
from feed2toot.main import Main

if __name__ == '__main__':
    Main()
    sys.exit(0)
